bank_app/urls.py
from django .urls import path

from bank_app import views
app_name = 'bank_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('bank/', views.home, name='bank'),

]

bank_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bank_app.urls')),
    path('admin/', admin.site.urls),
    path('credentials/', include('credentials.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credentials/urls.py
from django.urls import path

from credentials import views

app_name = 'credentials'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('inform/', views.inform, name='inform'),
    path('personal_details_form/',views.personal_details_form, name='details_form'),
    path('ajax/load_branches/',views.load_branches,name='ajax_branch_url'),
    path('logout/', views.logout, name='logout')

]

bank_app/models.py
from django.db import models
from django.urls import reverse


class Blog(models.Model):
    name = models.CharField(max_length=250)
    decsription = models.TextField()
    image = models.ImageField(upload_to='blog_images')

    def __str__(self):
        return self.name



class Branch(models.Model):
    branch_name = models.CharField(max_length=70, unique=True)
    link = models.URLField(unique=True, blank=True)
    def __str__(self):
        return self.branch_name

    # def get_url(self):
    #     return reverse('slug_path', args=[self.slug])

credentials/models.py
from django.db import models
from django.urls import reverse


class Register(models.Model):
    username = models.CharField(max_length=250, default=True)
    password = models.TextField()
    conform_password = models.TextField()

    def __str__(self):
        return self.username


class Districts(models.Model):
    name = models.CharField(max_length=250)


    def __str__(self):
        return self.name



class Branch(models.Model):
    district = models.ForeignKey(Districts, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class AccountType(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name





class FromTable(models.Model):
    name = models.CharField(max_length=50)
    date_of_birth = models.DateField(null=True,blank=True)
    age = models.PositiveIntegerField(null=True,blank=True)
    phone_number = models.CharField(max_length=20,blank=True)
    mail_id = models.EmailField(max_length=254,unique=True)
    address = models.TextField(blank=True)
    district = models.ForeignKey(Districts,on_delete=models.CASCADE)
    branch = models.ForeignKey(Branch,on_delete=models.CASCADE)
    account_type = models.ForeignKey(AccountType,on_delete=models.CASCADE)
    choices = models.ManyToManyField('CheckboxOptions', blank=True)


    def __str__(self):
        return self.name


class CheckboxOptions(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

credentials/forms.py
from django import forms
from . models import FromTable,Districts,Branch

class TableForm(forms.ModelForm):
    class Meta:
        model = FromTable
        fields = '__all__'

        widgets = {
            'name': forms.TextInput(attrs={ 'placeholder': 'enter you name', 'class': 'form-control ', 'style': 'width:250px;'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control','style': 'width:250px;','type': 'date'}),
            'age': forms.NumberInput(attrs={'class': 'form-control','style': 'width:250px;'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control','style': 'width:250px;'}),
            'mail_id': forms.EmailInput(attrs={'class': 'form-control','style': 'width:250px;','type':'email'}),
            'address': forms.Textarea(attrs={'class': 'form-control','style': 'width:250px;'}),
            'district':forms.Select(attrs={'class':'form-control','style': 'width:250px;'}),
            'branch': forms.Select(attrs={'class': 'form-control','style': 'width:250px;'}),
            'account_type': forms.Select(attrs={'class': 'form-control','style': 'width:250px;'}),
            'choices': forms.CheckboxSelectMultiple(attrs={'class': 'checkboxes','style': 'float:left'}),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['branch'].queryset = Branch.objects.none()

            # if 'country' in self.data:
            #     try:
            #         country_id = int(self.data.get('country'))
            #         self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            #     except (ValueError, TypeError):
            #         pass  # invalid input from the client; ignore and fallback to empty City queryset
            # elif self.instance.pk:
            #     self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

bank_app/views.py
from django.contrib.auth.models import User
from django.shortcuts import render,get_object_or_404
from .models import Branch,Blog


def home(request,c_slug=None):
    data=None
    blog = Blog.objects.all()
    branch = Branch.objects.all()
    for i in branch:
        print(i)
    return render(request, 'index.html',{'branches': branch,"blogs":blog})

credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.core.mail import message
from django.shortcuts import render, redirect
from .models import Register
from . forms import TableForm,Branch

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        conformpassword = request.POST['password2']
        if password == conformpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username already exists')
                return redirect('credentials:register')
            elif User.objects.filter(password=password).exists():
                messages.info(request,'password already exists')
                return redirect('credentials:register')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save();

                print('user created')
                return redirect('credentials:login')

        else:
            messages.info(request, 'user not created')
            return redirect('credentials:register')
        return redirect('/')
    return render(request, 'regist.html')


def login(request):
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        print('loggined')
        if user is not None:
            auth.login(request, user)
            return redirect('credentials:inform')
        else:
            messages.info(request, "invalid login")
            print('invalid login')
            return redirect('credentials:login')
    return render(request, 'login.html')



def logout(request):
    auth.logout(request)
    return redirect('/')

def inform(request):

    return render(request, 'informpage.html')


def personal_details_form(request):
    form = TableForm()
    if request.method == 'POST':
        form = TableForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            return redirect('credentials:details_form')
    return render(request, 'detailsform.html', {'form': form})


# AJAX
def load_branches(request):
    district_id = request.GET.get('district_id')
    branch = Branch.objects.filter(district_id=district_id).all()
    return render(request, 'dropdown.html', {'branches': branch})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

    <head>

        <!-- meta data -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <!--font-family-->
		<link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

        <!-- title of site -->
        <title>Directory Landing Page</title>

        <!-- For favicon png -->
		<link rel="shortcut icon" type="image/icon" href="{% static 'logo/favicon.png' %}"/>

        <!--font-awesome.min.css-->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

        <!--linear icon css-->
		<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">

		<!--animate.css-->
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">

		<!--flaticon.css-->
        <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">

		<!--slick.css-->
        <link rel="stylesheet" href="{% static 'css/slick.css' %}">
		<link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">

        <!--bootstrap.min.css-->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

		<!-- bootsnav -->
		<link rel="stylesheet" href="{% static 'css/bootsnav.css' %}" >

        <!--style.css-->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <!--responsive.css-->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

        <!--[if lt IE 9]>
		        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    <style>
            html,body{
            height:100%;
            padding:0;
            margin:0;

            }
.fixdiv{
		width:100%;
		}
.form1{
        width:480px;height:300px;margin-left:auto;margin-right:auto;margin-top:20px;border-radius:10px;border:10px;border:orange;

        }
.submit{text-align:center;margin-left:auto;margin-right:auto;
}
.submt{width:170px;height:40px;border-radius:10px;float:left;
}
.submt:hover{background-color:#0D7035;}

 .form1{
           width:480px;height:250px;margin-left:auto;margin-right:auto;margin-top:20px;border-radius:10px;border:10px;border:orange;

        }



</style>

    </head>

        <![endif]-->

		<!-- top-area Start -->
		<section class="top-area">
			<div class="header-area">
				<!-- Start Navigation -->
			    <nav class="navbar navbar-default bootsnav  navbar-sticky navbar-scrollspy"  data-minus-value-desktop="70" data-minus-value-mobile="55" data-speed="1000">

			        <div class="container">

			            <!-- Start Header Navigation -->
			            <div class="navbar-header">
			                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
			                    <i class="fa fa-bars"></i>
			                </button>
			                <a class="navbar-brand" href="index.html">FAITH<span>BANK</span></a>

			            </div><!--/.navbar-header-->
			            <!-- End Header Navigation -->

			            <!-- Collect the nav links, forms, and other content for toggling -->
			            <div class="collapse navbar-collapse menu-ui-design" >
			                <ul class="nav navbar-nav navbar-right" >
			                    <li class=" scroll active"><a href="#home">HOME</a></li>
			                    <li class="scroll"><a href="#works">SERVICES</a></li>
								   <li class="dropdown">
									<a>BRANCH</a>
								  <ul class="dropdown-menu">
									  <li><a href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Malappuram">Malapuram</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Kollam">Kollam</a></li>
								  </ul></li>
			                    <li class="scroll"><a href="#blog">news</a></li>
			                    <li class="scroll"><a href="#footer">contact</a></li>
								{% if user.is_authenticated %}
									<li><a href="credentials/logout" class=" btn nav-item nav-link">Logout</a></li>
								{% else %}
                    			<li><a href="credentials/login" class=" btn nav-item nav-link">Login</a></li>
                    			<li><a href="credentials/register" class="nav-item nav-link">register</a></li>
								{% endif %}
			                </ul><!--/.nav -->
			            </div><!-- /.navbar-collapse -->
			        </div><!--/.container-->
			    </nav><!--/nav-->
			    <!-- End Navigation -->
			</div><!--/.header-area-->
		    <div class="clearfix"></div>

		</section><!-- /.top-area-->
		<!-- top-area End -->
        {% block content %}
        {% endblock %}

    		<!--footer start-->
		<footer id="footer"  class="footer">
			<div class="container" style="width:100%;">
				<div class="hm-footer-copyright">
					<div class="row">
						<div class="col-sm-5">
							<p>
								&copy;copyright. designed and developed by <a href="https://www.themesine.com/">themesine</a>
							</p><!--/p-->
						</div>
						<div class="col-sm-7">
							<div class="footer-social">
								<span><i class="fa fa-phone"> +1  (222) 777 8888</i></span>
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-linkedin"></i></a>
								<a href="#"><i class="fa fa-google-plus"></i></a>
							</div>
						</div>
					</div>

				</div><!--/.hm-footer-copyright-->
			</div><!--/.container-->

			<div id="scroll-Top">
				<div class="return-to-top">
					<i class="fa fa-angle-up " id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
				</div>

			</div><!--/.scroll-Top-->

        </footer><!--/.footer-->
		<!--footer end-->

		<!-- Include all js compiled plugins (below), or include individual files as needed -->

		<script src="{% static 'js/jquery.js' %}"></script>

        <!--modernizr.min.js-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

		<!--bootstrap.min.js-->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

		<!-- bootsnav js -->
		<script src="{% static 'js/bootsnav.js' %}"></script>

        <!--feather.min.js-->
        <script  src="{% static 'js/feather.min.js' %}"></script>

        <!-- counter js -->
		<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
		<script src="{% static 'js/waypoints.min.js' %}"></script>

        <!--slick.min.js-->
        <script src="{% static 'js/slick.min.js' %}"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

        <!--Custom JS-->
        <script src="{% static 'js/custom.js' %}"></script>

    </body>

</html>

templates/base1.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

    <head>

        <!-- meta data -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <!--font-family-->
		<link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

        <!-- title of site -->
        <title>Directory Landing Page</title>

        <!-- For favicon png -->
		<link rel="shortcut icon" type="image/icon" href="{% static 'logo/favicon.png' %}"/>

        <!--font-awesome.min.css-->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

        <!--linear icon css-->
		<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">

		<!--animate.css-->
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">

		<!--flaticon.css-->
        <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">

		<!--slick.css-->
        <link rel="stylesheet" href="{% static 'css/slick.css' %}">
		<link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">

        <!--bootstrap.min.css-->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

		<!-- bootsnav -->
		<link rel="stylesheet" href="{% static 'css/bootsnav.css' %}" >

        <!--style.css-->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <!--responsive.css-->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

        <!--[if lt IE 9]>
		        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    <style>
            html,body{
            height:100%;
            padding:0;
            margin:0;

            }
.fixdiv{
		width:100%;
		}
.form1{
        width:480px;height:300px;margin-left:auto;margin-right:auto;margin-top:20px;border-radius:10px;border:10px;border:orange;

        }
.submit{text-align:center;margin-left:auto;margin-right:auto;
}
.submt{width:170px;height:40px;border-radius:10px;float:left;
}
.submt:hover{background-color:#0D7035;}

 .form1{
           width:480px;height:250px;margin-left:auto;margin-right:auto;margin-top:20px;border-radius:10px;border:10px;border:orange;

        }



</style>

    </head>

        <![endif]-->

		<!-- top-area Start -->
		<section class="top-area">
			<div class="header-area">
				<!-- Start Navigation -->
			    <nav class="navbar navbar-default bootsnav  navbar-sticky navbar-scrollspy"  data-minus-value-desktop="70" data-minus-value-mobile="55" data-speed="1000">

			        <div class="container">

			            <!-- Start Header Navigation -->
			            <div class="navbar-header">
			                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
			                    <i class="fa fa-bars"></i>
			                </button>
			                <a class="navbar-brand" href="index.html">FAITH<span>BANK</span></a>

			            </div><!--/.navbar-header-->
			            <!-- End Header Navigation -->

			            <!-- Collect the nav links, forms, and other content for toggling -->
			            <div class="collapse navbar-collapse menu-ui-design" >
			                <ul class="nav navbar-nav navbar-right" >
			                    <li class="active"><a href="{% url 'bank_app:home' %}">HOME</a></li>
								   <li class="dropdown">
									<a>BRANCH</a>
								  <ul class="dropdown-menu">
									  <li><a href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Malappuram">Malapuram</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Kollam">Kollam</a></li>
								  </ul></li>
			                    <li class="scroll"><a href="#footer">contact</a></li>
								{% if user.is_authenticated %}
									<li><a href="{% url 'credentials:logout' %}" class=" btn nav-item nav-link">Logout</a></li>
								{% else %}
                    			<li><a href="credentials/login" class=" btn nav-item nav-link">Login</a></li>
                    			<li><a href="credentials/register" class="nav-item nav-link">register</a></li>
								{% endif %}
			                </ul><!--/.nav -->
			            </div><!-- /.navbar-collapse -->
			        </div><!--/.container-->
			    </nav><!--/nav-->
			    <!-- End Navigation -->
			</div><!--/.header-area-->
		    <div class="clearfix"></div>

		</section><!-- /.top-area-->
		<!-- top-area End -->
        {% block content %}
        {% endblock %}

    		<!--footer start-->
		<footer id="footer"  class="footer">
			<div class="container" style="width:100%;">
				<div class="hm-footer-copyright">
					<div class="row">
						<div class="col-sm-5">
							<p>
								&copy;copyright. designed and developed by <a href="https://www.themesine.com/">themesine</a>
							</p><!--/p-->
						</div>
						<div class="col-sm-7">
							<div class="footer-social">
								<span><i class="fa fa-phone"> +1  (222) 777 8888</i></span>
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-linkedin"></i></a>
								<a href="#"><i class="fa fa-google-plus"></i></a>
							</div>
						</div>
					</div>

				</div><!--/.hm-footer-copyright-->
			</div><!--/.container-->

			<div id="scroll-Top">
				<div class="return-to-top">
					<i class="fa fa-angle-up " id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
				</div>

			</div><!--/.scroll-Top-->

        </footer><!--/.footer-->
		<!--footer end-->

		<!-- Include all js compiled plugins (below), or include individual files as needed -->

		<script src="{% static 'js/jquery.js' %}"></script>

        <!--modernizr.min.js-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

		<!--bootstrap.min.js-->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

		<!-- bootsnav js -->
		<script src="{% static 'js/bootsnav.js' %}"></script>

        <!--feather.min.js-->
        <script  src="{% static 'js/feather.min.js' %}"></script>

        <!-- counter js -->
		<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
		<script src="{% static 'js/waypoints.min.js' %}"></script>

        <!--slick.min.js-->
        <script src="{% static 'js/slick.min.js' %}"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

        <!--Custom JS-->
        <script src="{% static 'js/custom.js' %}"></script>

    </body>

</html>

templates/detailsform.html
{% extends 'base1.html' %}
{% block content %}
<div style="
  outline: solid 1px black;
  display: flex;
  justify-content: center;">
<div style="justify-content: center;display: flex;border-style: solid;outline: solid 1px black;width:950px;height:auto;">
<form action="{% url 'credentials:details_form' %}" class="form-horizontal col-md-10 " id="dataform" data-cities-url="{% url 'credentials:ajax_branch_url' %}" style="text-align:center;padding-top:10px;" method="post">
    {% csrf_token %}
        <div style="text-align:center;margin-top:25px;margin-bottom:25px;">
            <h1 style="font-family:Times New Roman;font-size:30px;">Please fill this form for further process</h1>
        </div>
       <div class="form-group row">
        <label  class="col-sm-4 col-form-label">{{ form.name.label }}:</label>
        <div class="col-sm-8">
            {{ form.name }}
        </div>
    </div>
    <div class="form-group row">
        <label  class="col-sm-4 col-form-label">{{ form.date_of_birth.label }}:</label>
        <div class="col-sm-8">
            {{ form.date_of_birth }}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-4 col-form-label">{{ form.age.label}}:</label>
        <div class="col-sm-8">
            {{form.age}}

        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-4 col-form-label">{{ form.phone_number.label}}:</label>
        <div class="col-sm-8">
            {{form.phone_number}}

        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-4 col-form-label">{{ form.mail_id.label}}:</label>
        <div class="col-sm-8">
            {{form.mail_id}}

        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-4 col-form-label">{{ form.address.label}}:</label>
        <div class="col-sm-8">
            {{form.address}}

        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-4 col-form-label">{{ form.district.label}}:</label>
        <div class="col-sm-8">
            {{form.district}}

        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-4 col-form-label">{{ form.branch.label}}:</label>
        <div class="col-sm-8">
            {{form.branch}}

        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-4 col-form-label">{{ form.account_type.label}}:</label>
        <div class="col-sm-8">
            {{form.account_type}}

        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-4 col-form-label">
            {{ form.choices.label}}:
        </label>
        <div class="col-sm-8">
            {% for choice in form.choices %}
        <div  style="float:left;padding:5px;">
            {{choice}}
        </div>
            {% endfor %}
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#dataform").attr("data-cities-url");  // get the url of the `load_cities` view
        const districtId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'district_id': districtId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_branch").html(data);  // replace the contents of the city input with the data that came from the server


<!--                let html_data = '<option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>';-->
<!--                data.forEach(function (city) {-->
<!--                    html_data += `<option value="${city.id}">${city.name}</option>`-->
<!--                });-->
<!--                console.log(html_data);-->
<!--                $("#id_city").html(html_data);-->


            }
        });

    });
</script>
    <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Submit</button>
      <button type="submit" class="btn btn-primary">Logout</button>
    </div>
  </div>
</form>
</div>
</div>
{% endblock %}

templates/dropdown.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}